name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install LuaRocks
        run: sudo apt update && sudo apt install luarocks

      - name: Install dependencies
        run: sudo luarocks install claf-1.0.0-1.rockspec
        
      - name: Run tests
        run: ./maint.lua test
        
      - name: Lint
        run: ./maint.lua lint
