name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Lua 5.2 and LuaRocks
        run: sudo apt update && sudo apt install lua5.2 liblua5.2-dev luarocks

      - run: chmod +x maint.lua

      - name: Install dependencies
        run: ./maint.lua prepare-ci

      - name: Check formatting
        run: ./maint.lua format-check

      - name: Run tests
        run: ./maint.lua test

      - name: Lint
        run: ./maint.lua lint
